[ADD] adds a new wiki tab with the history of pandora
Project-Pandora-Game/pandora pull request #441
Opened 2023-11-05 21:41 UTC by ClaudiaMia

This page can also be linked on Discord when users ask about how Pandora came to be and who is involved.
It should also answer potentially frequently asked questions in advance.

2023-11-05 23:28 UTC, Sekkmer requested changes

2023-11-05 23:28 UTC, Sekkmer commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +				In early 2021, most BC developers at that time concluded that they do not want to support BC any more, as they see various issues with it that
`anymore` is one word

2023-11-05 23:28 UTC, Sekkmer commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +				In a way, Pandora will offer an improved "classic" experience, focusing on roleplaying and clear house rules. It will not be tolerated that
`not be tolerated` to me this feels a bit strong, like as if we would plan to ban/kick whoever cheats

intent here is that we will ensure that cheating is not possible since we use server-side validations, I feel the wording could indicate it better

2023-11-05 23:28 UTC, Sekkmer commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +				In August 2021, "Project Pandora" officially started with the creation of the Pandora Discord.<br />
`Pandora Discord` could be a link

2023-11-05 23:28 UTC, Sekkmer commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +						develop it without the explicit permission by every person who ever contributed to BC which makes that almost impossible. The longevity of BC is
`permission by` -> `permission of`

2023-11-05 23:28 UTC, Sekkmer commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +					<li>Legality of assets/images: In BC there is no process for vetoing assets. Most of them are not providing where they originate
maybe: `are not providing` -> `do not provide`

2023-11-06 07:14 UTC, ClaudiaMia commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +				In early 2021, most BC developers at that time concluded that they do not want to support BC any more, as they see various issues with it that
Changed, thank you.

2023-11-06 07:15 UTC, ClaudiaMia commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +				In a way, Pandora will offer an improved "classic" experience, focusing on roleplaying and clear house rules. It will not be tolerated that
Yes, I actually had doubts about this part, I now feel much happier with it.

2023-11-06 07:15 UTC, ClaudiaMia commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +				In August 2021, "Project Pandora" officially started with the creation of the Pandora Discord.<br />
Changed, thank you.

2023-11-06 07:15 UTC, ClaudiaMia commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +						develop it without the explicit permission by every person who ever contributed to BC which makes that almost impossible. The longevity of BC is
Changed, thank you.

2023-11-06 07:15 UTC, ClaudiaMia commented on pandora-client-web/src/components/wiki/pages/history.tsx
> +					<li>Legality of assets/images: In BC there is no process for vetoing assets. Most of them are not providing where they originate
Changed, thank you.

2023-11-06 20:06 UTC, Sekkmer approved these changes

2023-11-06 20:19 UTC, merged