[ADD] asset preference and item coloring permissions
Project-Pandora-Game/pandora pull request #517
Opened 2024-01-12 13:15 UTC by Sekkmer

2024-01-12 19:12 UTC, Jomshir98 requested changes

2024-01-12 19:12 UTC, Jomshir98 commented on pandora-common/src/character/restrictionsManager.ts
> +					context.addInteraction(target.character, 'assetPrefFavorite');
Should they really be fallthrough? I'm not fully sure~

2024-01-12 19:12 UTC, Jomshir98 commented on pandora-common/src/gameLogic/interactions/_interactionConfig.ts
> +	},
I'm not sure about these being part of interactions config... I would rather move them to be their own category. If you wouldn't mind I can implement that as I have a good idea how to do that. (I intended for the solution to be used that way, but there is so far no example of how I actually imagined it being done)

2024-01-12 19:12 UTC, Jomshir98 commented on pandora-common/src/assets/appearanceActions.ts
>  			}
Thought: Maybe worth moving this interaction check into `canUseItem` when the interaction type is `STYLING`? That type is only used for coloring right now (and in theory for modules that mark themselves as styling, which makes sense for some modules like light/dark variant).

2024-01-13 13:18 UTC, Sekkmer commented on pandora-common/src/gameLogic/assetPreferences/assetPreferencesSubsystem.ts
> +	public abstract getPreferencePermission(preference: AssetPreferenceType): GameLogicPermission | null;
This feels like a complete duplication of the other Subsystem, but for some reason, this function can return null, the other throws an exception.

What exactly do we gain from this much extra duplicated code, if we just want to split it for the UI, a simple group in the config would have been able to accomplish the same thing with much less code

2024-01-14 12:19 UTC, Sekkmer commented on pandora-common/src/gameLogic/assetPreferences/assetPreferencesSubsystem.ts
> +	public abstract getPreferencePermission(preference: AssetPreferenceType): GameLogicPermission | null;
well I tried this but over all it did not make anything better, the duplication should be fine for now, I guess

2024-01-14 22:56 UTC, Jomshir98 approved these changes

2024-01-14 22:56 UTC, merged