[FEATURE] device module permission
Project-Pandora-Game/pandora pull request #737
Opened 2024-04-25 19:08 UTC by Sekkmer

2024-04-25 22:02 UTC, ClaudiaMia requested changes
Exclusive locks currently do not work despite the new binding. Does not matter who adds it. The person in the character slot that should be locked into the slot due to the lock module can simply unlock the exclusive lock.

2024-04-25 22:58 UTC, Sekkmer commented
> Exclusive locks currently do not work despite the new binding. Does not matter who adds it. The person in the character slot that should be locked into the slot due to the lock module can simply unlock the exclusive lock.

now that I think about it it may be due to the other bug that device modules do not effect the one inside

2024-04-26 20:05 UTC, ClaudiaMia approved these changes
Tested that exclusive locks now work correctly and also tested other things, such as deploying a device with a character inside that the admin has no permissions to interact with.

Found no issues.

2024-04-30 20:46 UTC, Jomshir98 approved these changes

2024-04-30 21:53 UTC, merged