[FEATURE] New attribute 'limit'
Project-Pandora-Game/pandora pull request #775
Opened 2024-05-23 08:18 UTC by SandrinePDR

This change adds a new attribute `limit` to assets that denotes, how many items o…f this kind can be worn at the same time.

As a proof of concept I added a limit of 20 to the pantyhose asset:

<img width="417" alt="image" src="https://github.com/Project-Pandora-Game/pandora/assets/118102950/3cfbed0f-b911-4a48-8a34-fc89418a1de8">

2024-05-24 18:47 UTC, Sekkmer requested changes

2024-05-27 06:36 UTC, SandrinePDR commented on pandora-common/src/assets/appearanceValidation.ts
> +		const limit = item.asset.definition.attributes?.limit ?? 1;
Tbh, I like exactly that flexibility. So nylons can be worn in abundance, woolen socks or T-shirts perhaps only two or three at a time and only one jeans. As long as we leave the default to one, I think, we are on the safe side.
But I think, we should clarify this now and change the PoC in the asset-repo accordingly and not do the work twice.

2024-05-27 14:07 UTC, Sekkmer commented on pandora-common/src/assets/appearanceValidation.ts
> +		const limit = item.asset.definition.attributes?.limit ?? 1;
this was more of a though then an required thing to change, in either case we can always change things later if we feel things getting out of hand

2024-05-27 14:12 UTC, Sekkmer commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
the reason for moving it to `PersonalAssetDefinition` is that it only make sense for those kind of assets

room devices are unlimited in the room anyway
room device wearable part can only be one as a time, enforced by logic in a different way
lock assets are also limited to being a single per module slot

2024-05-27 14:24 UTC, ClaudiaMia commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
To add to that, I personally also thought that there is no need to define any limits per asset with this change.
All assets that are not limited by other mechanics can be unlimited. If someone wants to use all 50 slots on a character to add 50 top hats, I guess that is their choice. It is easy enough to remove them by clicking 50 times, if someone else does this to you as a joke or to annoy.

Whatever individual asset limits we would add here to try to meet some subjective view of realism, there would always be someone saying, "hey, why can I only layer 10 ropes over the body".

2024-05-27 14:38 UTC, SandrinePDR commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
So you would rather go without any limit?
Because I think it would be better if we go with some safety line here.

2024-05-27 15:33 UTC, ClaudiaMia commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
Well, I simply feel it there is not much benefit to make this asset specific and let asset creators set something. This just invites inconsistencies and angry user comments.

So I feel it should be one attribute for assets that can be added onto a character body (so not furnitures as Sekkmer pointed out). I feel for now we can go with no limit, but if this invites abuse later on when we maybe increase the overall wardrobe limit from 50 to something like 100, then we can think of adding some global limit per asset, like 20. 

But I am not sure that would solve anything, as people then will simply add different types of lockable items in larger quantities to annoy.

What is your concern here? Why do you think we need a "life line"? Just curious to understand your thinking.

2024-05-27 15:35 UTC, SandrinePDR commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
That's the point of a life line... you have them just in case something weird happens. But I'm fine with not having a limit.

2024-05-27 15:37 UTC, ClaudiaMia commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
I mean if it is as easy to implement to have a specific limit, such as 20, as a life line, then we can surely also start with such a global arbitrary limit and then see if it is needed or not over time.

I feel neutral about this part. I doubt I would personally see a need to add a single item more than 20 times~ *giggles*

2024-05-27 15:39 UTC, ClaudiaMia commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
But considering Sekkmer's points, I got the impression that having no limit for now is much cleaner and lower effort coding wise. But you know this of course much better, as I did not look into the code.

2024-05-27 15:40 UTC, SandrinePDR commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
Sekkmer - as always - knows best...

2024-05-27 16:16 UTC, Sekkmer commented on pandora-common/src/assets/properties.ts
> +		limit?: number;
yep no limit feels like a good solution

2024-05-27 16:16 UTC, Sekkmer approved these changes

2024-05-27 16:27 UTC, merged